//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Teams.Apps.DIConnect.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Teams.Apps.DIConnect.Common.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stay updated on communications around diversity and inclusion.
        /// </summary>
        public static string AboutGroupsBulletText {
            get {
                return ResourceManager.GetString("AboutGroupsBulletText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact your IT admin for permission to view this data..
        /// </summary>
        public static string AdminConsentError {
            get {
                return ResourceManager.GetString("AdminConsentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Not Installed.
        /// </summary>
        public static string AppNotInstalled {
            get {
                return ResourceManager.GetString("AppNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to approve.
        /// </summary>
        public static string Approve {
            get {
                return ResourceManager.GetString("Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        public static string ApproveButtonText {
            get {
                return ResourceManager.GetString("ApproveButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New group suggested.
        /// </summary>
        public static string ApproveCardRequestSubmitted {
            get {
                return ResourceManager.GetString("ApproveCardRequestSubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        public static string ApprovedText {
            get {
                return ResourceManager.GetString("ApprovedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D&amp;I connect.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat with {0}.
        /// </summary>
        public static string ChatWithMatchButtonText {
            get {
                return ResourceManager.GetString("ChatWithMatchButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a rating.
        /// </summary>
        public static string ChoiceSetPlaceholder {
            get {
                return ResourceManager.GetString("ChoiceSetPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Status.
        /// </summary>
        public static string ColumnName_DeliveryStatus {
            get {
                return ResourceManager.GetString("ColumnName_DeliveryStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exported By.
        /// </summary>
        public static string ColumnName_ExportedBy {
            get {
                return ResourceManager.GetString("ColumnName_ExportedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export TimeStamp.
        /// </summary>
        public static string ColumnName_ExportTimeStamp {
            get {
                return ResourceManager.GetString("ColumnName_ExportTimeStamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Title.
        /// </summary>
        public static string ColumnName_MessageTitle {
            get {
                return ResourceManager.GetString("ColumnName_MessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent TimeStamp.
        /// </summary>
        public static string ColumnName_SentTimeStamp {
            get {
                return ResourceManager.GetString("ColumnName_SentTimeStamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Reason.
        /// </summary>
        public static string ColumnName_StatusReason {
            get {
                return ResourceManager.GetString("ColumnName_StatusReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team ID.
        /// </summary>
        public static string ColumnName_TeamId {
            get {
                return ResourceManager.GetString("ColumnName_TeamId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Name.
        /// </summary>
        public static string ColumnName_TeamName {
            get {
                return ResourceManager.GetString("ColumnName_TeamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPN.
        /// </summary>
        public static string ColumnName_Upn {
            get {
                return ResourceManager.GetString("ColumnName_Upn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID.
        /// </summary>
        public static string ColumnName_UserId {
            get {
                return ResourceManager.GetString("ColumnName_UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ColumnName_UserName {
            get {
                return ResourceManager.GetString("ColumnName_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure matches.
        /// </summary>
        public static string ConfigureMatchesCommand {
            get {
                return ResourceManager.GetString("ConfigureMatchesCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage match settings.
        /// </summary>
        public static string ConfigureNotificationCardButtonText {
            get {
                return ResourceManager.GetString("ConfigureNotificationCardButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;ve paused your matches.
        /// </summary>
        public static string ConfigureNotificationCardTitle {
            get {
                return ResourceManager.GetString("ConfigureNotificationCardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string ConfigureUserMatchesCardButtonText {
            get {
                return ResourceManager.GetString("ConfigureUserMatchesCardButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn matching on or off for each group.
        /// </summary>
        public static string ConfigureUserMatchesCardTitle {
            get {
                return ResourceManager.GetString("ConfigureUserMatchesCardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by.
        /// </summary>
        public static string CreatedByNameText {
            get {
                return ResourceManager.GetString("CreatedByNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared.
        /// </summary>
        public static string CreatedOn {
            get {
                return ResourceManager.GetString("CreatedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter feedback to help us improve the experience.
        /// </summary>
        public static string DescriptionPlaceHolderText {
            get {
                return ResourceManager.GetString("DescriptionPlaceHolderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string DescriptionText {
            get {
                return ResourceManager.GetString("DescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover employee groups in your org.
        /// </summary>
        public static string DiscoverGroupsBulletText {
            get {
                return ResourceManager.GetString("DiscoverGroupsBulletText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover groups.
        /// </summary>
        public static string DiscoverGroupsButtonText {
            get {
                return ResourceManager.GetString("DiscoverGroupsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (copy).
        /// </summary>
        public static string DuplicateText {
            get {
                return ResourceManager.GetString("DuplicateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. please try after sometime..
        /// </summary>
        public static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. Try exporting the results again..
        /// </summary>
        public static string ExportFailureText {
            get {
                return ResourceManager.GetString("ExportFailureText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        public static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create conversation. Error message: {0}.
        /// </summary>
        public static string FailedToCreateConversationFormat {
            get {
                return ResourceManager.GetString("FailedToCreateConversationFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create conversation with teams user: {0}. Exception: {1}.
        /// </summary>
        public static string FailedToCreateConversationForUserFormat {
            get {
                return ResourceManager.GetString("FailedToCreateConversationForUserFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create conversation. Request throttled. Error message: {0}&quot;.
        /// </summary>
        public static string FailedToCreateConversationThrottledFormt {
            get {
                return ResourceManager.GetString("FailedToCreateConversationThrottledFormt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to find the team {0} in DB..
        /// </summary>
        public static string FailedToFindTeamInDbFormat {
            get {
                return ResourceManager.GetString("FailedToFindTeamInDbFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to sync all users. Status Code: {0} Exception: {1}.
        /// </summary>
        public static string FailedToGetAllUsersFormat {
            get {
                return ResourceManager.GetString("FailedToGetAllUsersFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get conversation id for user: {0}. Status Code: {1} Exception: {2}.
        /// </summary>
        public static string FailedToGetConversationForUserFormat {
            get {
                return ResourceManager.GetString("FailedToGetConversationForUserFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get members for group {0}: {1}.
        /// </summary>
        public static string FailedToGetMembersForGroupFormat {
            get {
                return ResourceManager.GetString("FailedToGetMembersForGroupFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get members for team {0}: {1}.
        /// </summary>
        public static string FailedToGetMembersForTeamFormat {
            get {
                return ResourceManager.GetString("FailedToGetMembersForTeamFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to install application for user: {0}. Exception: {1}.
        /// </summary>
        public static string FailedToInstallApplicationForUserFormat {
            get {
                return ResourceManager.GetString("FailedToInstallApplicationForUserFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to prepare the message for sending:{0}.
        /// </summary>
        public static string FailtoPrepareMessageFormat {
            get {
                return ResourceManager.GetString("FailtoPrepareMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        public static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        public static string FeedbackDescriptionTitleText {
            get {
                return ResourceManager.GetString("FeedbackDescriptionTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Someone from the Diversity and Inclusion team will respond via chat..
        /// </summary>
        public static string FeedbackHeaderText {
            get {
                return ResourceManager.GetString("FeedbackHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **{0}** submitted feedback.
        /// </summary>
        public static string FeedbackSubHeaderText {
            get {
                return ResourceManager.GetString("FeedbackSubHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for your feedback! I&apos;ve shared it with the team. This helps us learn and improve..
        /// </summary>
        public static string FeedbackSubmittedMessage {
            get {
                return ResourceManager.GetString("FeedbackSubmittedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate this answer (Required).
        /// </summary>
        public static string FeedbackTitleText {
            get {
                return ResourceManager.GetString("FeedbackTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This file contains the results you exported..
        /// </summary>
        public static string FileCardDescription {
            get {
                return ResourceManager.GetString("FileCardDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The link for this download has expired. Export the results again..
        /// </summary>
        public static string FileCardExpireText {
            get {
                return ResourceManager.GetString("FileCardExpireText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExportData.
        /// </summary>
        public static string FileName_ExportData {
            get {
                return ResourceManager.GetString("FileName_ExportData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message_Delivery.
        /// </summary>
        public static string FileName_Message_Delivery {
            get {
                return ResourceManager.GetString("FileName_Message_Delivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata.
        /// </summary>
        public static string FileName_Metadata {
            get {
                return ResourceManager.GetString("FileName_Metadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your file is ready to download. A copy is also available in OneDrive..
        /// </summary>
        public static string FileReadyText {
            get {
                return ResourceManager.GetString("FileReadyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. Try exporting the results again..
        /// </summary>
        public static string FileUploadErrorText {
            get {
                return ResourceManager.GetString("FileUploadErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get answers to questions you ask me in chat.
        /// </summary>
        public static string GetAnswersBulletText {
            get {
                return ResourceManager.GetString("GetAnswersBulletText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group already exist with same link and name. Please try with other.
        /// </summary>
        public static string GroupAlreadyExistsErrorMessage {
            get {
                return ResourceManager.GetString("GroupAlreadyExistsErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group created.
        /// </summary>
        public static string GroupCreated {
            get {
                return ResourceManager.GetString("GroupCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported bot command.
        /// </summary>
        public static string HelpCardHeaderText {
            get {
                return ResourceManager.GetString("HelpCardHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helpful.
        /// </summary>
        public static string HelpfulTitleText {
            get {
                return ResourceManager.GetString("HelpfulTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi there,.
        /// </summary>
        public static string InitiateChatText {
            get {
                return ResourceManager.GetString("InitiateChatText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only team members of the team can create resource group. Please contact your team owner for help..
        /// </summary>
        public static string InvalidGroupMemberErrorMessage {
            get {
                return ResourceManager.GetString("InvalidGroupMemberErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team not found with in the tenant.
        /// </summary>
        public static string InvalidTenantErrorMessage {
            get {
                return ResourceManager.GetString("InvalidTenantErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have requested to join the below ERG group. Please click here {0} to join the group.
        /// </summary>
        public static string JoinERGNotificationTaskModuleText {
            get {
                return ResourceManager.GetString("JoinERGNotificationTaskModuleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string LocationText {
            get {
                return ResourceManager.GetString("LocationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today, I&apos;ve matched you with {0}, a member of {1}. As a next step, make a selection below:.
        /// </summary>
        public static string MatchUpCardContentPart1 {
            get {
                return ResourceManager.GetString("MatchUpCardContentPart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you&apos;ve got the inclination, set something up. See, meeting people *is* easy!.
        /// </summary>
        public static string MatchUpCardContentPart2 {
            get {
                return ResourceManager.GetString("MatchUpCardContentPart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m the Diversity and Inclusion chatbot, and I can help you meet other people in the employee groups you&apos;ve joined..
        /// </summary>
        public static string MatchUpCardMatchedText {
            get {
                return ResourceManager.GetString("MatchUpCardMatchedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s time for a match!.
        /// </summary>
        public static string MatchUpCardTitleContent {
            get {
                return ResourceManager.GetString("MatchUpCardTitleContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meet people in the groups you join.
        /// </summary>
        public static string MeetPeopleBulletText {
            get {
                return ResourceManager.GetString("MeetPeopleBulletText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hey there, looks like we&apos;ve been matched by {0} this week. It&apos;d be great to meet up for a coffee or a lunch or a call if you&apos;ve got time..
        /// </summary>
        public static string MeetupContent {
            get {
                return ResourceManager.GetString("MeetupContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduction Meet up.
        /// </summary>
        public static string MeetupTitle {
            get {
                return ResourceManager.GetString("MeetupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string NameText {
            get {
                return ResourceManager.GetString("NameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Needs improvement.
        /// </summary>
        public static string NeedsImprovementTitleText {
            get {
                return ResourceManager.GetString("NeedsImprovementTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We haven&apos;t found any matching answer for your question. .
        /// </summary>
        public static string NoMatchesFoundText {
            get {
                return ResourceManager.GetString("NoMatchesFoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No active matches to manage settings..
        /// </summary>
        public static string NoMatchesToManageText {
            get {
                return ResourceManager.GetString("NoMatchesToManageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string NoText {
            get {
                return ResourceManager.GetString("NoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not helpful.
        /// </summary>
        public static string NotHelpfulTitleText {
            get {
                return ResourceManager.GetString("NotHelpfulTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The notification has {0} groups as its recipients. It shouldn&apos;t exceed {1} groups..
        /// </summary>
        public static string NumberOfGroupsExceededLimitWarningFormat {
            get {
                return ResourceManager.GetString("NumberOfGroupsExceededLimitWarningFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The notification has {0} rosters as its recipients. It shouldn&apos;t exceed {1} rosters..
        /// </summary>
        public static string NumberOfRostersExceededLimitWarningFormat {
            get {
                return ResourceManager.GetString("NumberOfRostersExceededLimitWarningFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The notification has {0} teams as its recipients. It shouldn&apos;t exceed {1} teams..
        /// </summary>
        public static string NumberOfTeamsExceededLimitWarningFormat {
            get {
                return ResourceManager.GetString("NumberOfTeamsExceededLimitWarningFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause matches.
        /// </summary>
        public static string PauseMatchesButtonText {
            get {
                return ResourceManager.GetString("PauseMatchesButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause matches.
        /// </summary>
        public static string PauseMatchesCommand {
            get {
                return ResourceManager.GetString("PauseMatchesCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause matches.
        /// </summary>
        public static string PauseMatchesText {
            get {
                return ResourceManager.GetString("PauseMatchesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending approval.
        /// </summary>
        public static string PendingApprovalText {
            get {
                return ResourceManager.GetString("PendingApprovalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission declined. We will not proceed with the export..
        /// </summary>
        public static string PermissionDeclinedText {
            get {
                return ResourceManager.GetString("PermissionDeclinedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here are some of the &quot;Follow-up questions&quot; you might be interested. .
        /// </summary>
        public static string PromptHeaderText {
            get {
                return ResourceManager.GetString("PromptHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send meeting invite.
        /// </summary>
        public static string ProposeMeetupButtonText {
            get {
                return ResourceManager.GetString("ProposeMeetupButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipient Not Found.
        /// </summary>
        public static string RecipientNotFound {
            get {
                return ResourceManager.GetString("RecipientNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        public static string RejectButtonText {
            get {
                return ResourceManager.GetString("RejectButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected.
        /// </summary>
        public static string RejectedText {
            get {
                return ResourceManager.GetString("RejectedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New group suggested.
        /// </summary>
        public static string RequestSubmittedText {
            get {
                return ResourceManager.GetString("RequestSubmittedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The employee resource group entity that user is trying to update does not exist.
        /// </summary>
        public static string ResourceGroupNotExistsErrorMessage {
            get {
                return ResourceManager.GetString("ResourceGroupNotExistsErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee resource group entity cannot be null..
        /// </summary>
        public static string ResourceGroupNullOrEmptyErrorMessage {
            get {
                return ResourceManager.GetString("ResourceGroupNullOrEmptyErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here&apos;s what I found on this topic:.
        /// </summary>
        public static string ResponseHeaderText {
            get {
                return ResourceManager.GetString("ResponseHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your matches are resumed.
        /// </summary>
        public static string ResumeCardTitle {
            get {
                return ResourceManager.GetString("ResumeCardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage matching settings.
        /// </summary>
        public static string ResumeMatchesButtonText {
            get {
                return ResourceManager.GetString("ResumeMatchesButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage matching settings.
        /// </summary>
        public static string ResumeMatchesCommand {
            get {
                return ResourceManager.GetString("ResumeMatchesCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search enabled.
        /// </summary>
        public static string SearchEnabledText {
            get {
                return ResourceManager.GetString("SearchEnabledText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send notification.
        /// </summary>
        public static string SendNotification {
            get {
                return ResourceManager.GetString("SendNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        public static string ShareButtonText {
            get {
                return ResourceManager.GetString("ShareButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share feedback.
        /// </summary>
        public static string ShareFeedbackText {
            get {
                return ResourceManager.GetString("ShareFeedbackText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succeeded.
        /// </summary>
        public static string Succeeded {
            get {
                return ResourceManager.GetString("Succeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string TagText {
            get {
                return ResourceManager.GetString("TagText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Throttled.
        /// </summary>
        public static string Throttled {
            get {
                return ResourceManager.GetString("Throttled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot command is not supported..
        /// </summary>
        public static string UnSupportedBotCommand {
            get {
                return ResourceManager.GetString("UnSupportedBotCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot command is not supported..
        /// </summary>
        public static string UnsupportedBotCommandText {
            get {
                return ResourceManager.GetString("UnsupportedBotCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage matching settings.
        /// </summary>
        public static string UpdateCardButtonTitle {
            get {
                return ResourceManager.GetString("UpdateCardButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All set! You can manage your settings at any time..
        /// </summary>
        public static string UpdateCardTitle {
            get {
                return ResourceManager.GetString("UpdateCardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update matches.
        /// </summary>
        public static string UpdateMatchesCommand {
            get {
                return ResourceManager.GetString("UpdateMatchesCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m the Diversity and Inclusion chatbot, and I&apos;m here to help you:.
        /// </summary>
        public static string WelcomeHeaderText {
            get {
                return ResourceManager.GetString("WelcomeHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello there!.
        /// </summary>
        public static string WelcomeTitleText {
            get {
                return ResourceManager.GetString("WelcomeTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string YesText {
            get {
                return ResourceManager.GetString("YesText", resourceCulture);
            }
        }
    }
}
